### ISSUE TITLE
Add Translation to Pokedex

### ISSUE THREAD

**Issue by yfartel** [PcBoy111/PCBOT#5]
Hi, firstly thanks for your job ! 

Currently i'm using your hosted version of Botémon and want to use it with another language, should be a nice idea to add a translation of the pokedex. 

I can help you to translate in french. 

Thanks for your time.

**Comment by pckv** [comment]
Hello, 

while I think it's a nice idea, it seems more bothersome to implement than neccessary. This would require:
* french .csv files for compiling a french specific pokedex.json
* loading both the english and the french pokedex.json (would take more resources since they're kinda big)
* making a command to change language settings, which would *only* affect the pokedex plugin.

The last point is my biggest concern, as if you want to have a french pokedex, it would only be natural for the entire bot to have a french setting. Currently, it doesn't. Botemon is built on my personal pcbot, which doesn't have any support for multiple languages. This means that command info would always be english regardless. Therefore I think there will be a disconnect between languages.

I think there might be too much effort involved to implement this feature, especially if you're doing it alone. However, if you really want to try, you can start by compiling an english equivalent of the pokedex.json. Check the pokedexlib for source files.
